[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycalculator_dapp = "CEtJEtnhHw4VJQUbEAd4u2fUBjxiAUpnszmR6TNjsxWE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/roster/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.*"
